# Generated by Django 5.2.4 on 2026-08-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Billing', 'Billing'), ('Feature Request', 'Feature Request'), ('General', 'General')], default='Technical', max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=30)),
                ('description', models.TextField()),
                ('assignee', models.CharField(blank=True, default='', max_length=200)),
                ('messages', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
